// FinanceNexus/src/components/Layout/Sidebar.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import {
  LayoutDashboard,
  Receipt,
  Calculator,
  PiggyBank,
  TrendingUp,
  Settings,
  Menu,
  X,
  LockKeyhole,
} from 'lucide-react';
import { motion } from 'framer-motion';

const navItems = [
  { path: '/', icon: LayoutDashboard, label: '仪表盘' },
  { path: '/transactions', icon: Receipt, label: '记账' },
  { path: '/tax', icon: Calculator, label: '税务' },
  { path: '/investments', icon: PiggyBank, label: '理财' },
  { path: '/simulator', icon: TrendingUp, label: '复利模拟' },
  { path: '/settings', icon: Settings, label: '设置' },
];

export function Sidebar() {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <motion.aside
      initial={{ width: collapsed ? 80 : 260 }}
      animate={{ width: collapsed ? 80 : 260 }}
      transition={{ duration: 0.3, ease: 'easeInOut' }}
      className="relative h-screen glass-card border-r border-primary-200/30 flex flex-col"
    >
      <div className="flex items-center justify-between p-4 border-b border-primary-200/20">
        {!collapsed && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex items-center gap-3"
          >
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-sky-500 flex items-center justify-center">
              <LockKeyhole className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="font-display font-bold text-lg gradient-text">FinanceNexus</h1>
              <p className="text-xs text-primary-400">智能财务管理</p>
            </div>
          </motion.div>
        )}
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="p-2 rounded-lg hover:bg-primary-100/50 transition-colors"
        >
          {collapsed ? <Menu className="w-5 h-5" /> : <X className="w-5 h-5" />}
        </button>
      </div>

      <nav className="flex-1 p-3 space-y-1 overflow-y-auto scrollbar-thin">
        {navItems.map((item, index) => (
          <NavLink
            key={item.path}
            to={item.path}
            end={item.path === '/'}
            className={({ isActive }) =>
              `flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 group ${
                isActive
                  ? 'bg-gradient-to-r from-emerald-500/20 to-sky-500/20 text-emerald-400 border border-emerald-500/30'
                  : 'hover:bg-primary-100/50 text-primary-400 hover:text-white'
              }`
            }
          >
            {({ isActive }) => (
              <>
                <item.icon
                  className={`w-5 h-5 flex-shrink-0 transition-transform ${
                    isActive ? 'scale-110' : 'group-hover:scale-110'
                  }`}
                />
                {!collapsed && (
                  <motion.span
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="font-medium text-sm whitespace-nowrap"
                  >
                    {item.label}
                  </motion.span>
                )}
              </>
            )}
          </NavLink>
        ))}
      </nav>

      {!collapsed && (
        <div className="p-4 border-t border-primary-200/20">
          <div className="glass-card-hover rounded-xl p-4">
            <p className="text-xs text-primary-400 mb-2">数据安全</p>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-sm text-emerald-400">本地加密存储</span>
            </div>
          </div>
        </div>
      )}
    </motion.aside>
  );
}

// SleepMatrix/src/components/layout/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import {
  LayoutDashboard,
  LineChart,
  Archive,
  Settings,
  Cpu,
  BarChart3,
  Moon,
} from 'lucide-solid';
import { cn } from '@/lib/utils';

interface NavItem {
  path: string;
  label: string;
  icon: Component<{ class?: string }>;
}

const navItems: NavItem[] = [
  { path: '/', label: '仪表盘', icon: LayoutDashboard },
  { path: '/analysis', label: '关联分析', icon: LineChart },
  { path: '/visualize', label: '数据可视化', icon: BarChart3 },
  { path: '/archive', label: '睡眠档案', icon: Archive },
  { path: '/devices', label: '设备管理', icon: Cpu },
  { path: '/settings', label: '系统设置', icon: Settings },
];

export const Sidebar: Component = () => {
  const location = useLocation();

  const isActive = (path: string) => {
    if (path === '/') return location.pathname === '/';
    return location.pathname.startsWith(path);
  };

  return (
    <aside class="w-64 bg-midnight-900/80 backdrop-blur-xl border-r border-midnight-700/50 flex flex-col h-full">
      <div class="p-6 border-b border-midnight-700/50">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-moon-500 to-moon-600 flex items-center justify-center shadow-lg shadow-moon-500/30">
            <Moon class="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 class="text-lg font-bold text-white font-display">SleepMatrix</h1>
            <p class="text-xs text-midnight-400">智能睡眠分析</p>
          </div>
        </div>
      </div>

      <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
        {navItems.map(item => (
          <A
            href={item.path}
            class={cn(
              'flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 group',
              isActive(item.path)
                ? 'bg-moon-500/20 text-moon-400 shadow-lg shadow-moon-500/10'
                : 'text-midnight-300 hover:bg-midnight-800/50 hover:text-white'
            )}
          >
            <item.icon
              class={cn(
                'w-5 h-5 transition-transform group-hover:scale-110',
                isActive(item.path) && 'text-moon-400'
              )}
            />
            <span class="font-medium">{item.label}</span>
            {isActive(item.path) && (
              <div class="ml-auto w-1.5 h-1.5 rounded-full bg-moon-400 animate-pulse" />
            )}
          </A>
        ))}
      </nav>

      <div class="p-4 border-t border-midnight-700/50">
        <div class="bg-gradient-to-r from-midnight-800/80 to-midnight-800/40 rounded-xl p-4 backdrop-blur-sm">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-8 h-8 rounded-full bg-mint-500/20 flex items-center justify-center">
              <div class="w-3 h-3 rounded-full bg-mint-400 animate-pulse" />
            </div>
            <div>
              <p class="text-sm font-medium text-white">系统运行中</p>
              <p class="text-xs text-midnight-400">实时数据流正常</p>
            </div>
          </div>
          <div class="flex gap-2">
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">CPU</p>
              <p class="text-sm font-semibold text-mint-400">23%</p>
            </div>
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">内存</p>
              <p class="text-sm font-semibold text-moon-400">412MB</p>
            </div>
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">连接</p>
              <p class="text-sm font-semibold text-amber-400">4</p>
            </div>
          </div>
        </div>
      </div>
    </aside>
  );
};
