// HomeAutoPulset/src/components/common/Sidebar.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
  LayoutDashboard,
  AlertTriangle,
  GitMerge,
  Database,
  Settings2,
  Cpu,
  Settings,
  Activity,
  Shield,
  Home,
} from 'lucide-vue-next';

const route = useRoute();
const router = useRouter();

const navItems = [
  { path: '/', name: '监控仪表盘', icon: LayoutDashboard },
  { path: '/conflicts', name: '冲突解析中心', icon: AlertTriangle },
  { path: '/semantic', name: '语义对齐配置', icon: GitMerge },
  { path: '/snapshots', name: '设备快照管理', icon: Database },
  { path: '/rules', name: '规则引擎配置', icon: Settings2 },
  { path: '/devices', name: '设备列表', icon: Cpu },
  { path: '/settings', name: '系统设置', icon: Settings },
];

const isActive = (path: string) => {
  if (path === '/') return route.path === '/';
  return route.path.startsWith(path);
};

const navigate = (path: string) => {
  router.push(path);
};

const systemStatus = computed(() => ({
  online: true,
  lastSync: Date.now(),
}));
</script>

<template>
  <aside class="fixed left-0 top-0 h-full w-64 bg-deep-space border-r border-slate-mid/30 flex flex-col z-50">
    <div class="p-6 border-b border-slate-mid/30">
      <div class="flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-neon-purple to-cyber-teal flex items-center justify-center shadow-lg shadow-neon-purple/20">
          <Activity class="w-5 h-5 text-white" />
        </div>
        <div>
          <h1 class="font-display text-lg font-bold text-white">HomeAutoPulse</h1>
          <p class="text-xs text-slate-light">智能家庭控制中心</p>
        </div>
      </div>
    </div>

    <div class="flex-1 overflow-y-auto py-4">
      <div class="px-4 mb-4">
        <div class="flex items-center gap-2 px-3 py-2 bg-midnight/50 rounded-lg border border-success-green/20">
          <div class="relative">
            <div class="w-2 h-2 rounded-full bg-success-green"></div>
            <div class="absolute inset-0 rounded-full bg-success-green animate-ping opacity-75"></div>
          </div>
          <span class="text-xs text-success-green">系统运行正常</span>
        </div>
      </div>

      <nav class="space-y-1 px-3">
        <button
          v-for="item in navItems"
          :key="item.path"
          @click="navigate(item.path)"
          :class="[
            'w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm font-medium transition-all duration-200',
            isActive(item.path)
              ? 'bg-neon-purple/20 text-neon-purple border border-neon-purple/30 shadow-lg shadow-neon-purple/10'
              : 'text-slate-light hover:text-white hover:bg-midnight/50 border border-transparent'
          ]"
        >
          <component :is="item.icon" class="w-5 h-5" />
          <span>{{ item.name }}</span>
        </button>
      </nav>

      <div class="mt-8 px-6">
        <h3 class="text-xs font-semibold text-slate-light uppercase tracking-wider mb-3">快捷场景</h3>
        <div class="space-y-2">
          <div class="flex items-center gap-3 px-3 py-2 bg-midnight/30 rounded-lg hover:bg-midnight/50 cursor-pointer transition-colors">
            <Shield class="w-4 h-4 text-alert-orange" />
            <span class="text-sm text-slate-light">安防模式</span>
          </div>
          <div class="flex items-center gap-3 px-3 py-2 bg-midnight/30 rounded-lg hover:bg-midnight/50 cursor-pointer transition-colors">
            <Home class="w-4 h-4 text-info-blue" />
            <span class="text-sm text-slate-light">回家模式</span>
          </div>
        </div>
      </div>
    </div>

    <div class="p-4 border-t border-slate-mid/30">
      <div class="flex items-center gap-3">
        <div class="w-9 h-9 rounded-full bg-gradient-to-br from-neon-purple to-info-blue flex items-center justify-center">
          <span class="text-white font-semibold text-sm">管</span>
        </div>
        <div class="flex-1 min-w-0">
          <p class="text-sm font-medium text-white truncate">管理员</p>
          <p class="text-xs text-slate-light truncate">admin@homeauto.local</p>
        </div>
      </div>
    </div>
  </aside>
</template>

// SleepMatrix/src/components/layout/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';
import {
  LayoutDashboard,
  LineChart,
  Archive,
  Settings,
  Cpu,
  BarChart3,
  Moon,
} from 'lucide-solid';
import { cn } from '@/lib/utils';

interface NavItem {
  path: string;
  label: string;
  icon: Component<{ class?: string }>;
}

const navItems: NavItem[] = [
  { path: '/', label: '仪表盘', icon: LayoutDashboard },
  { path: '/analysis', label: '关联分析', icon: LineChart },
  { path: '/visualize', label: '数据可视化', icon: BarChart3 },
  { path: '/archive', label: '睡眠档案', icon: Archive },
  { path: '/devices', label: '设备管理', icon: Cpu },
  { path: '/settings', label: '系统设置', icon: Settings },
];

export const Sidebar: Component = () => {
  const location = useLocation();

  const isActive = (path: string) => {
    if (path === '/') return location.pathname === '/';
    return location.pathname.startsWith(path);
  };

  return (
    <aside class="w-64 bg-midnight-900/80 backdrop-blur-xl border-r border-midnight-700/50 flex flex-col h-full">
      <div class="p-6 border-b border-midnight-700/50">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-moon-500 to-moon-600 flex items-center justify-center shadow-lg shadow-moon-500/30">
            <Moon class="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 class="text-lg font-bold text-white font-display">SleepMatrix</h1>
            <p class="text-xs text-midnight-400">智能睡眠分析</p>
          </div>
        </div>
      </div>

      <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
        {navItems.map(item => (
          <A
            href={item.path}
            class={cn(
              'flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 group',
              isActive(item.path)
                ? 'bg-moon-500/20 text-moon-400 shadow-lg shadow-moon-500/10'
                : 'text-midnight-300 hover:bg-midnight-800/50 hover:text-white'
            )}
          >
            <item.icon
              class={cn(
                'w-5 h-5 transition-transform group-hover:scale-110',
                isActive(item.path) && 'text-moon-400'
              )}
            />
            <span class="font-medium">{item.label}</span>
            {isActive(item.path) && (
              <div class="ml-auto w-1.5 h-1.5 rounded-full bg-moon-400 animate-pulse" />
            )}
          </A>
        ))}
      </nav>

      <div class="p-4 border-t border-midnight-700/50">
        <div class="bg-gradient-to-r from-midnight-800/80 to-midnight-800/40 rounded-xl p-4 backdrop-blur-sm">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-8 h-8 rounded-full bg-mint-500/20 flex items-center justify-center">
              <div class="w-3 h-3 rounded-full bg-mint-400 animate-pulse" />
            </div>
            <div>
              <p class="text-sm font-medium text-white">系统运行中</p>
              <p class="text-xs text-midnight-400">实时数据流正常</p>
            </div>
          </div>
          <div class="flex gap-2">
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">CPU</p>
              <p class="text-sm font-semibold text-mint-400">23%</p>
            </div>
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">内存</p>
              <p class="text-sm font-semibold text-moon-400">412MB</p>
            </div>
            <div class="flex-1 bg-midnight-900/60 rounded-lg px-2 py-1.5 text-center">
              <p class="text-[10px] text-midnight-400">连接</p>
              <p class="text-sm font-semibold text-amber-400">4</p>
            </div>
          </div>
        </div>
      </div>
    </aside>
  );
};
