// QuantumGate/src/components/Sidebar.tsx
import { Component } from 'solid-js';
import { A, useLocation } from '@solidjs/router';

interface NavItem {
  path: string;
  label: string;
  icon: string;
}

const navItems: NavItem[] = [
  { path: '/dashboard', label: '监控仪表盘', icon: '📊' },
  { path: '/rabi-oscillation', label: '拉比振荡', icon: '📈' },
  { path: '/fidelity', label: '保真度计算', icon: '⚛️' },
  { path: '/error-correction', label: '量子纠错', icon: '🔄' },
  { path: '/settings', label: '系统设置', icon: '⚙️' },
];

export const Sidebar: Component = () => {
  const location = useLocation();

  return (
    <aside class="w-64 h-full glass-card border-r border-quantum-cyan/20 flex flex-col">
      <div class="p-6 border-b border-white/10">
        <div class="flex items-center gap-3">
          <div class="w-10 h-10 rounded-lg bg-quantum-cyan/20 flex items-center justify-center text-2xl">
            ⚛️
          </div>
          <div>
            <h1 class="text-lg font-display font-bold text-white neon-text">QuantumGate</h1>
            <p class="text-xs text-quantum-cyan/70 font-mono">v1.0.0</p>
          </div>
        </div>
      </div>

      <nav class="flex-1 p-4 overflow-y-auto">
        <ul class="space-y-2">
          {navItems.map((item) => {
            const isActive = location.pathname === item.path;
            return (
              <li>
                <A
                  href={item.path}
                  class={`
                    flex items-center gap-3 px-4 py-3 rounded-md transition-all duration-300
                    ${isActive 
                      ? 'bg-quantum-cyan/20 text-quantum-cyan border border-quantum-cyan/30' 
                      : 'text-white/60 hover:bg-white/5 hover:text-white border border-transparent'
                    }
                  `}
                >
                  <span class="text-xl">{item.icon}</span>
                  <span class="font-mono text-sm">{item.label}</span>
                  {isActive && <span class="ml-auto w-1.5 h-1.5 rounded-full bg-quantum-cyan animate-pulse" />}
                </A>
              </li>
            );
          })}
        </ul>
      </nav>

      <div class="p-4 border-t border-white/10">
        <div class="flex items-center gap-3 px-4 py-3 rounded-md bg-white/5">
          <div class="w-8 h-8 rounded-full bg-quantum-purple/30 flex items-center justify-center text-sm">
            👤
          </div>
          <div class="flex-1 min-w-0">
            <p class="text-sm font-medium text-white truncate">研究员</p>
            <p class="text-xs text-white/50 font-mono truncate">research@quantum-lab</p>
          </div>
        </div>
      </div>
    </aside>
  );
};

// FinanceNexus/src/components/Layout/Sidebar.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import {
  LayoutDashboard,
  Receipt,
  Calculator,
  PiggyBank,
  TrendingUp,
  Settings,
  Menu,
  X,
  LockKeyhole,
} from 'lucide-react';
import { motion } from 'framer-motion';

const navItems = [
  { path: '/', icon: LayoutDashboard, label: '仪表盘' },
  { path: '/transactions', icon: Receipt, label: '记账' },
  { path: '/tax', icon: Calculator, label: '税务' },
  { path: '/investments', icon: PiggyBank, label: '理财' },
  { path: '/simulator', icon: TrendingUp, label: '复利模拟' },
  { path: '/settings', icon: Settings, label: '设置' },
];

export function Sidebar() {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <motion.aside
      initial={{ width: collapsed ? 80 : 260 }}
      animate={{ width: collapsed ? 80 : 260 }}
      transition={{ duration: 0.3, ease: 'easeInOut' }}
      className="relative h-screen glass-card border-r border-primary-200/30 flex flex-col"
    >
      <div className="flex items-center justify-between p-4 border-b border-primary-200/20">
        {!collapsed && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex items-center gap-3"
          >
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-emerald-500 to-sky-500 flex items-center justify-center">
              <LockKeyhole className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="font-display font-bold text-lg gradient-text">FinanceNexus</h1>
              <p className="text-xs text-primary-400">智能财务管理</p>
            </div>
          </motion.div>
        )}
        <button
          onClick={() => setCollapsed(!collapsed)}
          className="p-2 rounded-lg hover:bg-primary-100/50 transition-colors"
        >
          {collapsed ? <Menu className="w-5 h-5" /> : <X className="w-5 h-5" />}
        </button>
      </div>

      <nav className="flex-1 p-3 space-y-1 overflow-y-auto scrollbar-thin">
        {navItems.map((item, index) => (
          <NavLink
            key={item.path}
            to={item.path}
            end={item.path === '/'}
            className={({ isActive }) =>
              `flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200 group ${
                isActive
                  ? 'bg-gradient-to-r from-emerald-500/20 to-sky-500/20 text-emerald-400 border border-emerald-500/30'
                  : 'hover:bg-primary-100/50 text-primary-400 hover:text-white'
              }`
            }
          >
            {({ isActive }) => (
              <>
                <item.icon
                  className={`w-5 h-5 flex-shrink-0 transition-transform ${
                    isActive ? 'scale-110' : 'group-hover:scale-110'
                  }`}
                />
                {!collapsed && (
                  <motion.span
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="font-medium text-sm whitespace-nowrap"
                  >
                    {item.label}
                  </motion.span>
                )}
              </>
            )}
          </NavLink>
        ))}
      </nav>

      {!collapsed && (
        <div className="p-4 border-t border-primary-200/20">
          <div className="glass-card-hover rounded-xl p-4">
            <p className="text-xs text-primary-400 mb-2">数据安全</p>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-sm text-emerald-400">本地加密存储</span>
            </div>
          </div>
        </div>
      )}
    </motion.aside>
  );
}
