// SleepMatrix/src/components/cards/StatCard.tsx
import { Component, ParentProps } from 'solid-js';
import { Motion } from '@motionone/solid';
import { cn } from '@/lib/utils';

interface StatCardProps extends ParentProps {
  title: string;
  value: string | number;
  subtitle?: string;
  icon: Component<{ class?: string }>;
  trend?: {
    value: number;
    isPositive: boolean;
  };
  color?: 'moon' | 'mint' | 'amber' | 'rose' | 'blue';
  class?: string;
}

const colorClasses = {
  moon: {
    bg: 'from-moon-500/10 to-moon-600/5',
    border: 'border-moon-500/20',
    icon: 'text-moon-400 bg-moon-500/20',
    trend: 'text-moon-400',
  },
  mint: {
    bg: 'from-mint-500/10 to-mint-600/5',
    border: 'border-mint-500/20',
    icon: 'text-mint-400 bg-mint-500/20',
    trend: 'text-mint-400',
  },
  amber: {
    bg: 'from-amber-500/10 to-amber-600/5',
    border: 'border-amber-500/20',
    icon: 'text-amber-400 bg-amber-500/20',
    trend: 'text-amber-400',
  },
  rose: {
    bg: 'from-rose-500/10 to-rose-600/5',
    border: 'border-rose-500/20',
    icon: 'text-rose-400 bg-rose-500/20',
    trend: 'text-rose-400',
  },
  blue: {
    bg: 'from-blue-500/10 to-blue-600/5',
    border: 'border-blue-500/20',
    icon: 'text-blue-400 bg-blue-500/20',
    trend: 'text-blue-400',
  },
};

export const StatCard: Component<StatCardProps> = (props) => {
  const colors = colorClasses[props.color ?? 'moon'];

  return (
    <Motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      class={cn(
        'relative p-6 rounded-2xl border backdrop-blur-xl overflow-hidden group',
        'bg-gradient-to-br',
        colors.bg,
        colors.border,
        'hover:shadow-lg hover:shadow-moon-500/5 transition-all duration-300',
        props.class
      )}
    >
      <div class="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

      <div class="relative flex items-start justify-between mb-4">
        <div class={cn(
          'p-3 rounded-xl transition-transform group-hover:scale-110 duration-300',
          colors.icon
        )}>
          <props.icon class="w-6 h-6" />
        </div>
        {props.trend && (
          <div class={cn(
            'flex items-center gap-1 px-2 py-1 rounded-lg text-xs font-medium',
            props.trend.isPositive ? 'bg-mint-500/10 text-mint-400' : 'bg-rose-500/10 text-rose-400'
          )}>
            <span>{props.trend.isPositive ? '↑' : '↓'}</span>
            <span>{Math.abs(props.trend.value)}%</span>
          </div>
        )}
      </div>

      <div class="relative">
        <p class="text-sm text-midnight-400 mb-1">{props.title}</p>
        <p class="text-3xl font-bold text-white font-display tracking-tight">
          {props.value}
        </p>
        {props.subtitle && (
          <p class="text-xs text-midnight-500 mt-1">{props.subtitle}</p>
        )}
      </div>

      {props.children && (
        <div class="relative mt-4 pt-4 border-t border-midnight-700/30">
          {props.children}
        </div>
      )}
    </Motion.div>
  );
};

// AviaFlow/src/components/common/StatCard.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Component } from 'vue';

const props = withDefaults(defineProps<{
  title: string;
  value: string | number;
  icon: Component;
  trend?: number;
  color?: 'blue' | 'green' | 'amber' | 'red' | 'purple';
  subtitle?: string;
}>(), {
  color: 'blue',
  trend: 0,
});

const colorClasses = computed(() => {
  const colors: Record<string, string> = {
    blue: 'from-blue-500 to-cyan-500 text-blue-400 bg-blue-600/10 border-blue-500/30',
    green: 'from-green-500 to-emerald-500 text-green-400 bg-green-600/10 border-green-500/30',
    amber: 'from-amber-500 to-orange-500 text-amber-400 bg-amber-600/10 border-amber-500/30',
    red: 'from-red-500 to-rose-500 text-red-400 bg-red-600/10 border-red-500/30',
    purple: 'from-purple-500 to-fuchsia-500 text-purple-400 bg-purple-600/10 border-purple-500/30',
  };
  return colors[props.color];
});

const bgGradient = computed(() => {
  const gradients: Record<string, string> = {
    blue: 'from-blue-500 to-cyan-400',
    green: 'from-green-500 to-emerald-400',
    amber: 'from-amber-500 to-orange-400',
    red: 'from-red-500 to-rose-400',
    purple: 'from-purple-500 to-fuchsia-400',
  };
  return gradients[props.color];
});
</script>

<template>
  <div class="bg-slate-800/50 backdrop-blur-sm border border-slate-700/50 rounded-2xl p-5 hover:border-slate-600/50 transition-all hover:shadow-lg hover:shadow-slate-900/50">
    <div class="flex items-start justify-between">
      <div class="flex-1 min-w-0">
        <div class="text-sm font-medium text-slate-400 mb-1">{{ title }}</div>
        <div class="text-3xl font-bold text-slate-100 mb-2">{{ value }}</div>
        <div v-if="subtitle" class="text-xs text-slate-500">{{ subtitle }}</div>
        <div v-if="trend !== 0" class="flex items-center gap-1 mt-2">
          <span
            class="text-xs font-medium"
            :class="trend > 0 ? 'text-green-400' : 'text-red-400'"
          >
            {{ trend > 0 ? '↑' : '↓' }} {{ Math.abs(trend) }}%
          </span>
          <span class="text-xs text-slate-500">较昨日</span>
        </div>
      </div>
      <div
        class="w-12 h-12 rounded-xl bg-gradient-to-br flex items-center justify-center"
        :class="[bgGradient, 'bg-opacity-20']"
      >
        <component :is="icon" class="w-6 h-6 text-white" />
      </div>
    </div>
  </div>
</template>
